### ISSUE TITLE
to_list is broken

### ISSUE THREAD

**Issue by santosh79** [SenecaSystems/red_black_tree#8]
```
tree = RedBlackTree.new |>
          RedBlackTree.insert("one", 1) |>
          RedBlackTree.insert("two", 2) |>
          RedBlackTree.insert("three", 3) 

assert [{"one", 1}, {"two", 2}, {"three", 3}] === (tree |> RedBlackTree.to_list)
```
NOTE: This test fails.

**Comment by tyre** [comment]
Red Black Trees are sorted by their keys. This should come back as `[{"one", 1}, {"three", 3}, {"two", 2}]`, since `"th"` comes before `"tw"`

**Comment by santosh79** [comment]
Hi Chris,
I think I had the keys and scores mixed up. Makes sense.

Thanks!

Santosh

**Comment by santosh79** [comment]
Chris,
This may be a silly question but when I do:

```
RedBlackTree.new |>
          RedBlackTree.insert("one", 1) |
```

Am I inserting item "one" with a score of "1".

**Comment by tyre** [comment]
Not a problem.

RedBlackTrees are key/value stores, similar to hashes/maps/dictionaries. So these two things are semantically almost identical:

```elixir
map = %{ "one" => 1, "two" => 2, "three" => 3 }
tree = RedBlackTree.new |>
          RedBlackTree.insert("one", 1) |>
          RedBlackTree.insert("two", 2) |>
          RedBlackTree.insert("three", 3)
``` 

Each one associates a  key (e.g. `"one"`) with a value (e.g. `1`). RedBlackTrees keep the keys sorted, while Elixir maps have an undefined order (if I recall correctly.)

RedBlackTrees don't have scores, similar to sorted sets in Redis. If you'd like a sorted set, I implemented one on top of this library [here](https://github.com/senecasystems/sorted_set). Unfortunately, this doesn't work like Redis sorted sets either (a key with a score.) It just keeps a set sorted.

If you need a set that is sorted by the values, you can implement that on top of this library. Check out the [Comparison section of the README](https://github.com/SenecaSystems/red_black_tree#comparison) for providing a custom comparator. The example there does what you want, keeping maps unique by `id` but ordered by `revenue`

**Comment by santosh79** [comment]
This is very useful and yes I am exactly looking for the Redis Sorted Sets implementation.

**Comment by tyre** [comment]
Great! Closing this issue but reach out with questions if you have them.
